
# theme settings
# theme                    : "minimal-mistakes-jekyll"
remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark" # "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise", "default"

# Site Settings
locale                   : "en-US"
title                    : "Dmitry Dolgov"
title_separator          : "-"
subtitle                 : Data Scientist and Project Manager
name                     : "Dmitry Dolgov"
description              : "Dmitry Dolgov"
words_per_minute         : 200

github: [metadata]

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-titles-from-headings
  - jekyll-remote-theme

titles_from_headings:
  enabled:     false
  strip_title: true
  collections: true 
  
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)

# Site Author
author:
  name             : Dmitry Dolgov
  avatar           : /assets/images/beard.jpg
  bio: 
    Data manager and project scientist
    <br>
    or is it the other way around?
    
  links:
    - label: "Vancouver, BC"
      icon: "fas fa-2x fa-fw fa-map-marker-alt"
      url: "https://goo.gl/maps/dDSS5zqqT8JTHRa57"
    - label: "Email"
      icon: "fas fa-2x fa-fw fa-envelope"
      url: "mailto:dmitry.m.dolgov@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-2x fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/dmdolgov/"    
    - label: "GitHub"
      icon: "fab fa-2x fa-fw fa-github"
      url: "https://github.com/dmitrytoda"
    - label: "Instagram"
      icon: "fab fa-2x fa-fw fa-instagram"
      url: "https://www.instagram.com/dmitrytoda/"

      
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/dmitrytoda"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/dmdolgov/"

      
include:
  - .htaccess
  - _pages
  
exclude:
  - /local
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
  
keep_files:
  - .git
  - .svn
  
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: false
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
